# fly.toml app configuration file generated for simple-web-test on 2024-04-22T22:13:17+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'simple-web-test'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 8123
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
